hystrix.stream.enabled = false
nats.addresses = ['nats://localhost:4222']
micronaut.session.http.coherence.enabled = true
elasticsearch.httpHosts = 'http://localhost:9200,http://127.0.0.2:9200'
hazelcast.network.addresses = "['121.0.0.1:5701']"
consul.client.registration.enabled = true
mongodb.uri = 'mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb'
rabbitmq.uri = 'amqp://localhost:5672'
redis.uri = 'redis://localhost'
flyway.datasources.default.enabled = true

[datasources.default]
url = 'jdbc:mariadb://localhost:3306/db'
username = 'root'
password = ''
driver-class-name = 'org.mariadb.jdbc.Driver'
db-type = 'mariadb'

[otel.traces]
exporter = 'jaeger,zipkin,otlp,logging'
propagator = 'tracecontext, baggage, xray'

[ribbon]
VipAddress = 'test'
ServerListRefreshInterval = 2000

[micronaut.security]
authentication = 'session'
token.jwt.signatures.secret.generator.secret = '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'

[mqtt.client]
server-uri = 'tcp://localhost:1883'
client-id = '${random.uuid}'
